import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "@/context/AuthContext";
import ReactQueryProvider from "./utils/ReactQueryProvider";
import Footer from "./components/Footer";
import { SearchProvider } from "@/context/SearchContext";





const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <AuthProvider>
            <SearchProvider>
              <Navbar />
              {children}
              <Footer />
            </SearchProvider>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
